services:
  db:
    image: postgres:14.4
    container_name: db_container
    ports:
      - ${PG_PORT_OUT}:${PG_PORT_IN}
    # We can use 'env_file: .env' too
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    volumes:
      - ./data/db_data:${PGDATA}:rw
  web:
    image: tomcat:9.0.65-jre17-temurin-jammy
    container_name: tomcat_container
    depends_on:
      - db
    ports:
      - ${TC_PORT_OUT}:${TC_PORT_IN}
    volumes:
      - ./target/webapps/:${WEB_APPS_PATH}:rw
      - ./data/tomcat_data/conf/:/usr/local/tomcat/conf/:rw
      - ./data/tomcat_data/logs/:/usr/local/tomcat/logs/:rw
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    ports:
      - ${PGADMIN_PORT_OUT}:${PGADMIN_PORT_IN}
    #We can use 'env_file: .env' too
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    volumes:
      - ./data/pgadmin_data:/var/lib/pgadmin:rw
