INSERT INTO product(category_name, name, unit_price, is_active) VALUES('Yoğurt', 'Kova Yoğurt 2000g', 36.95, true );
INSERT INTO product(category_name, name, unit_price, is_active) VALUES('Peynir', 'Kaşar Peyniri 400g', 48.95, false );
INSERT INTO product(category_name, name, unit_price, is_active) VALUES('Yoğurt', 'Kaymaklı Tava Yoğurt 1000g', 29.95, true );
INSERT INTO product(category_name, name, unit_price, is_active) VALUES('Yoğurt', 'Efsane Yoğurt 350g', 12.95, true );
INSERT INTO product(category_name, name, unit_price, is_active) VALUES('Yoğurt', 'Süzme Yoğurt 250g', 25.95, false );
INSERT INTO product(category_name, name, unit_price, is_active) VALUES('Ayran', 'Eker Ayran 1000ml', 13.95, true );
INSERT INTO product(category_name, name, unit_price, is_active) VALUES('Kefir', 'Ananaslı Kefir 200ml', 6.95, true );
INSERT INTO product(category_name, name, unit_price, is_active) VALUES('Tatlı', 'Keşkül 150g', 9.95, true );
INSERT INTO product(category_name, name, unit_price, is_active) VALUES('Fırsat Paketleri', 'Sakızlı Muhallebi 6x150g', 49.75, true );
INSERT INTO product(category_name, name, unit_price, is_active) VALUES('Tatlı', 'Antep Fıstıklı Sütlü Çikolatalı Tatlı', 9.95, true );
INSERT INTO product(category_name, name, unit_price, is_active) VALUES('Tatlı', 'Hoşmerim 150g', 9.95, true );
