name: CI
on:
  push:
    branches:
      - master
      - main
      - doc
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: generate-file-tree
        run: printf '# File Tree\n```sh\n' > docs/file-tree.md && tree --gitignore >> docs/file-tree.md && sed -i -e '$d' docs/file-tree.md && echo '```' >> docs/file-tree.md
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
